Repository andreschoque3/Tax_website, pull requests merged in 2024-10, with the labels that each got.

#3 feat: initial commit 10/4
  Images/bg.jpg
  Images/slider-1.jpg
  Images/trucks.jpg
  Jobs/jobs.css
  Jobs/jobs.html
  Resources/resources.css
  Resources/resources.html
  Services/services.css
  Services/services.html
  Truckers/truckers.css
  Truckers/truckers.html
  index.css
  index.html
Labels: documentation

#4 Fake comments
  Services/services.css
  index.html
Labels: invalid

#6 feat: simplifying web design 10/11
  Images/jobs-bg.jpg
  Images/resources-bg.jpg
  Images/service-bg.jpg
  Jobs/jobs.css
  Jobs/jobs.html
  Resources/resources.css
  Resources/resources.html
  Services/services.css
  Services/services.html
  Truckers/truckers.css
  Truckers/truckers.html
  index.css
  index.html
Labels: enhancement

#7 improved home page 10/11
  Jobs/jobs.css
  Resources/resources.css
  Services/services.css
  Truckers/truckers.css
  index.css
  index.html
Labels: enhancement

#10 feat: Update for Truckers and Contact 1.0 10/18
  Contact/contact.css
  Contact/contact.html
  Services/services.css
  Truckers/truckers.css
  Truckers/truckers.html
  index.css
  index.html
Labels: enhancement

#9 Improvments toward Resources and Jobs Pages
  Images/client-p.jpg
  Images/jobs-bg.jpg
  Images/payment-p.jpg
  Jobs/jobs.css
  Jobs/jobs.html
  Resources/resources.css
  Resources/resources.html
Labels: enhancement

#11 feat: imrpoved Truckers 1.1 10/18
  Truckers/truckers.css
  Truckers/truckers.html
Labels: enhancement

#12 Refactored Home page
  Images/bg.jpg
  Images/foot-img1.png
  Images/foot-img2.png
  Images/foot-img3.png
  Images/foot-img4.png
  Images/foot-img5.png
  Images/foot-img6.png
  Images/footer-img.png
  Images/home-bg.jpg
  Images/resources-bg.jpg
  Images/seniors.jpg
  Images/slider-1.jpg
  Jobs/jobs.css
  Jobs/jobs.html
  Resources/resources.css
  Resources/resources.html
  index.css
  index.html
Labels: enhancement

#13 feat: Refactor Tax website
  Contact/contact.css
  Contact/contact.html
  Images/contact-bg.jpg
  Images/intro-img.jpg
  Images/service-bg.jpg
  Jobs/jobs.css
  Jobs/jobs.html
  Resources/resources.css
  Resources/resources.html
  Services/services.css
  Services/services.html
  Truckers/truckers.css
  Truckers/truckers.html
  index.css
  index.html
Labels: enhancement
